# Generated by Django 3.2.8 on 2022-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20220111_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
