# Generated by Django 3.2.8 on 2022-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_book_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dislikes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='book',
            name='viewers',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
