# Generated by Django 3.2.8 on 2022-01-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20220111_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dislikes',
        ),
    ]
