# Generated by Django 3.2.8 on 2022-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_remove_book_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/%Y/%m/%d'),
        ),
    ]
