# Generated by Django 3.2.8 on 2022-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, help_text='Файл(книга)', null=True, upload_to='books/files/%Y/%m/%d'),
        ),
    ]
